# Token types / constants
INTEGER            =   'INTEGER'
PLUS               =   'PLUS'
MINUS              =   'MINUS'
MULT               =   'MULT'
DIV                =   'DIV'
EOF                =   'EOF'
LPAREN             =   '('
RPAREN             =   ')'

LESS_THAN          =   'LESS_THAN'
LESS_THAN_EQUAL    =   'LESS_THAN_EQUAL'
EQUALS             =   'EQUALS'
GREATER_THAN       =   'GREATER_THAN'
GREATER_THAN_EQUAL =   'GREATER_THAN_EQUAL'

BEGIN              =   '{'
END                =   '}'
IF                 =   'IF'
FI                 =   'FI'
ELSE               =   'ELSE'
ELSEIF             =   'ELSEIF'
FOO                =   'FOO'
PRINT              =   'PRINT'
FOR                =   'FOR'
FUNC               =   'FUNC'
CALL               =   'CALL'

SEMI               =   'SEMI'
DOT                =   'DOT'
ASSIGN             =   'ASSIGN'
ID                 =   'ID'
STR                =   'STR'
COMMA              =   ','
